### PR TITLE
unsafe layout, refactoring tests, more tests, benchmarks,

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
all fields seems right(very important if somebody wants to manupulate fields), but padding sometimes inaccurate (see 3 commented out tests). there should be fix (some paper about padding-alignment algorithm on x84/ARM/CLR?), but I have not time to fix it now.

**Comment by dzmitry-lahoda** [comment]
I see some codes in `InspectorHelper` and `TypeLayout` for padding guesses. May be will use next time. 
So better to fix after #20 and I will need to split out code gen related pars from pure claculation-reflection.

**Comment by SergeyTeplyakov** [comment]
Thanks a lot for the PR, @dzmitry-lahoda, I'll review it later today.

**Comment by dzmitry-lahoda** [comment]
Meantime I have found meaningful (for me) hopefully correct definition of alignment I can work with https://ziglang.org/documentation/master/#Alignment

**Comment by dzmitry-lahoda** [comment]
I have reused padding calculator, so still padding are not correct for many scenarios (also improved).

**Comment by SergeyTeplyakov** [comment]
Thanks a lot!

**Pull request merged**
